# Generated by Django 2.1.3 on 2018-11-29 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkworld', '0004_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
