# Generated by Django 2.1.3 on 2018-12-02 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linkworld', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='score',
        ),
    ]
